analytics: {}
color:
  brandColors:
    - '#A0A0A8'
    - '#183858'
    - '#788088'
    - '#3780C8'
    - '#000000'
  brandStrength: 0.181588
  lightness: 0.625
  rhythmicContrast: 0.5
  saturation: 0.506757
cta: {}
layout_spectrum: 0.994088
name: 'Alex Halperin, Reporter'
opengraph: {}
purpose: []
typography_spectrum: 0.685811
