name: 'Alex Halperin, Reporter'
favicon: null
layout_spectrum: 0.75375
typography_spectrum: 0.5041432029101998
title: 'Alex Halperin, Reporter'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#868992'
    - '#a9acb1'
    - '#010100'
    - '#60687b'
    - '#3c2a1c'
  brandStrength: 0.27789529017172754
  lightness: 0.080566989723593
  saturation: 0.2674365579150617
  rhythmicContrast: 0.6893041047733277
purpose: []
