name: 'Alex Halperin, Reporter'
favicon: null
layout_spectrum: 0.7769769930746406
typography_spectrum: 0.5041432029101998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27789529017172754
  lightness: 0.080566989723593
  saturation: 0.2674365579150617
  rhythmicContrast: 0.6893041047733277
purpose: []
